[logger]
    level = "DEBUG"

[http]
    host = "localhost"
    port = 8080

[grpc]
    host = "localhost"
    port = 8082

[storage]
    type ="postgres" #memory / postgres
    migration = "/etc/migrations"

[database]
    host = "postgres"
    port = 5432
    dbname = "postgres"
    username = "postgres"
    password = "postgres"