[logger]
    level = "DEBUG"

[net]
    api = "grpc" #http / grpc
    host = "localhost"
    port = 8080

[storage]
    type ="postgres" #memory / postgres
    migration = "migrations" # 0

[database]
    host = "localhost"
    port = 5432
    dbname = "postgres"
    username = "postgres"
    password = "postgres"

[rabbitmq]
    host = "localhost"
    port = 5672
    user = "guest"
    password = "guest"