rmq:
  uri: "amqp://guest:guest@localhost:5672/"
  reConnect:
    maxElapsedTime: "1m"
    initialInterval: "1s"
    multiplier: 2
    maxInterval: "15s"

queues:
  events:
    exchangeName: "events"
    exchangeType: "fanout"
    queueName: "notifications"
    bindingKey: ""

producer:
  checkEventsToPublishInterval: "5s"
  checkOldEventsInterval: "20s"

database:
  host: "localhost"
  port: 5432
  dbname: "postgres"
  username: "postgres"
  password: "postgres"

logger:
  level: DEBUG