rmq:
  uri: "amqp://guest:guest@localhost:5672/"
  reConnect:
    maxElapsedTime: "1m"
    initialInterval: "1s"
    multiplier: 2
    maxInterval: "15s"

queues:
  events:
    exchangeName: "events"
    exchangeType: "fanout"
    queueName: "notifications"
    bindingKey: ""
  senders:
    exchangeName: "stats"
    exchangeType: "fanout"
    queueName: "senders"
    bindingKey: ""

consumer:
  consumerTag: "calendar_notifications_sender"
  qosPrefetchCount: 10
  threads: 4

database:
  host: "localhost"
  port: 5432
  dbname: "postgres"
  username: "postgres"
  password: "postgres"

logger:
  level: DEBUG