logger:
  level: DEBUG

storage:
  type: postgres #memory / postgres
  migration: "/etc/migrations"

database:
  host: "postgres"
  port: 5432
  dbname: "postgres"
  username: "postgres"
  password: "postgres"

rmq:
  uri: "amqp://guest:guest@localhost:5672/"
  reConnect:
    maxElapsedTime: "1m"
    initialInterval: "1s"
    multiplier: 2
    maxInterval: "15s"

queues:
  events:
    exchangeName: "events"
    exchangeType: "fanout"
    queueName: "notifications"
    bindingKey: ""

consumer:
  consumerTag: "calendar_notifications_sender"
  qosPrefetchCount: 10
  threads: 4
